"""
    Router interface — defines the protocol that all routers must implement.
"""

abstract type AbstractRouter end

"""
    StaticRouter — Base type for routers generated by `@router` macro.
    Routes are resolved at compile time via generated if/elseif dispatch.
"""
abstract type StaticRouter <: AbstractRouter end

# --- Router Protocol (required methods) ---

# dispatch_route(router, method, path) → Union{Nothing, RouteMatch}
# has_ws_routes(router) → Bool
# ws_endpoint(router, uri) → Union{Nothing, AbstractWsEndpoint}
# match_route_exact(router, method, path) → Union{Nothing, RouteMatch}

# Default: static routers have no WS routes (overridden by @router)
@inline has_ws_routes(::StaticRouter) = false
@inline match_route_exact(::StaticRouter, ::Symbol, ::AbstractString) = nothing

# Route count (for logging)
route_count(::StaticRouter) = "static"
