"""
    Static router — compile-time route dispatch via @router macro.
    Generates a monolithic Prefix Trie AST dispatch function for juliac --trim=safe AOT compilation.
    Zero runtime dispatch, zero allocation.
"""

"""
    StaticRouter — Base type for static app types generated by @router.
"""
abstract type StaticRouter <: AbstractRouter end

# By default, static routers have no WS routes. @router can override.
@inline _haswsroutes(::StaticRouter) = false

"""
    _dispatchstatic(app, request) → Response
"""
function _dispatchstatic end

# Interface fallback — @router generates the real methods
_dispatchstatic(app::T, ::AbstractRequest) where {T<:StaticRouter} =
    error("$(T) must implement _dispatchstatic via the @router macro")

# --- Path matching helpers (used by generated code) ---

@inline function _staticnextseg(path::AbstractString, start_idx::Int)
    len = ncodeunits(path)
    if start_idx > len
        return (view(path, 1:0), start_idx)
    end
    # skip leading slashes for normalization
    while start_idx <= len && codeunit(path, start_idx) == UInt8('/')
        start_idx += 1
    end
    if start_idx > len
        return (view(path, 1:0), start_idx)
    end

    # find next slash
    end_idx = start_idx
    while end_idx <= len && codeunit(path, end_idx) != UInt8('/')
        end_idx += 1
    end

    return (view(path, start_idx:end_idx-1), end_idx)
end

@inline function _stripquery(uri::AbstractString)
    len = ncodeunits(uri)
    for i in 1:len
        codeunit(uri, i) == UInt8('?') && return SubString(uri, 1, i - 1)
    end
    return SubString(uri, 1, len)
end

# --- Compile-time Types and Trie Construction ---
struct RouteSegment
    is_variable::Bool
    value::String
    type::Union{Type,Symbol}
end

mutable struct StaticNode
    static_children::Dict{String,StaticNode}
    variable_child::Union{Tuple{RouteSegment,StaticNode},Nothing}
    wildcard_child::Union{Tuple{String,StaticNode},Nothing}
    handler::Union{Expr,Symbol,Nothing}

    StaticNode() = new(Dict{String,StaticNode}(), nothing, nothing, nothing)
end

function _parseroute(path::String)
    segments = RouteSegment[]
    parts = split(path, '/', keepempty=false)
    for (i, part) in enumerate(parts)
        if startswith(part, "{") && endswith(part, "}")
            inner = part[2:end-1]
            if occursin("::", inner)
                name, typestr = split(inner, "::", limit=2)
                push!(segments, RouteSegment(true, String(name), Symbol(typestr)))
            else
                push!(segments, RouteSegment(true, String(inner), SubString{String}))
            end
        elseif startswith(part, ":")
            # Support :name syntax but convert to SubString for performance
            name = part[2:end]
            push!(segments, RouteSegment(true, String(name), SubString{String}))
        elseif startswith(part, "*")
            i < length(parts) && error("RouteError: wildcard segment *$(part[2:end]) must be the last segment in route \"$path\"")
            name = part[2:end]
            # Wildcards use type String to distinguish from SubString{String} single-segment variables.
            # The handler receives a SubString of the remaining path (everything from this segment to end).
            push!(segments, RouteSegment(true, String(name), String))
        else
            push!(segments, RouteSegment(false, String(part), Nothing))
        end
    end
    return segments
end

function _buildtrie(routes)
    root = StaticNode()
    for (method_sym, path, handler) in routes
        segments = _parseroute(path)
        # We model the method as the first segment essentially, to share the trie.
        method_seg = RouteSegment(false, String(method_sym), Nothing)
        segments = [method_seg; segments]

        node = root
        for seg in segments
            if seg.is_variable
                if seg.type == String  # wildcard *name — consumes rest of path
                    if node.wildcard_child === nothing
                        node.wildcard_child = (seg.value, StaticNode())
                    end
                    node = node.wildcard_child[2]
                else  # normal variable :name or {name}
                    if node.variable_child === nothing
                        node.variable_child = (seg, StaticNode())
                    end
                    node = node.variable_child[2]
                end
            else
                if !haskey(node.static_children, seg.value)
                    node.static_children[seg.value] = StaticNode()
                end
                node = node.static_children[seg.value]
            end
        end
        node.handler = handler
    end
    return root
end

function _generatedispatch(node::StaticNode, seg_sym::Symbol, idx_sym::Symbol, path_sym::Symbol, req_sym::Symbol, parsed_vars::Vector{Symbol}, is_root::Bool=false)
    exprs = []

    # 1. Exact match reached
    if node.handler !== nothing
        handler_call = Expr(:call, esc(node.handler), req_sym, parsed_vars...)
        push!(exprs, quote
            if length($(seg_sym)) == 0
                return $(handler_call)
            end
        end)
    end

    # 2. Static children
    if !isempty(node.static_children)
        static_blocks = []
        for (val, child) in node.static_children
            next_seg = gensym("seg")
            next_idx = gensym("idx")
            child_expr = _generatedispatch(child, next_seg, next_idx, path_sym, req_sym, parsed_vars)

            if is_root
                # At the root level the "segment" is the HTTP method — compare as Symbol
                # (zero allocation: Symbols are interned, comparison is pointer equality)
                method_sym_lit = Symbol(val)
                push!(static_blocks, quote
                    if $(req_sym).method == $(QuoteNode(method_sym_lit))
                        $(next_seg), $(next_idx) = _staticnextseg($(path_sym), 1)
                        $(child_expr)
                    end
                end)
            else
                push!(static_blocks, quote
                    if $(seg_sym) == $val
                        $(next_seg), $(next_idx) = _staticnextseg($(path_sym), $(idx_sym))
                        $(child_expr)
                    end
                end)
            end
        end
        push!(exprs, Expr(:block, static_blocks...))
    end

    # 3. Variable child
    if node.variable_child !== nothing
        seg, child = node.variable_child
        var_sym = gensym(seg.value)
        next_seg = gensym("seg")
        next_idx = gensym("idx")

        new_parsed_vars = copy(parsed_vars)
        push!(new_parsed_vars, var_sym)

        child_expr = _generatedispatch(child, next_seg, next_idx, path_sym, req_sym, new_parsed_vars)

        # In Mongoose, we default variables to SubString (zero-copy) for performance
        parse_expr = if seg.type == SubString{String} || seg.type == String || seg.type == :String
            quote
                $(var_sym) = $(seg_sym) # use the view directly
            end
        else
            quote
                $(var_sym) = Base.parse($(seg.type), String($(seg_sym)))
            end
        end

        push!(exprs, quote
            if length($(seg_sym)) != 0
                $(parse_expr)
                $(next_seg), $(next_idx) = _staticnextseg($(path_sym), $(idx_sym))
                $(child_expr)
            end
        end)
    end

    # 4. Wildcard child
    if node.wildcard_child !== nothing
        val, child = node.wildcard_child
        var_sym = gensym(val)
        new_parsed_vars = copy(parsed_vars)
        push!(new_parsed_vars, var_sym)

        # A wildcard captures the remainder of the path as a SubString (zero-copy).
        # idx_sym is the codeunit end_idx returned by _staticnextseg (one past seg end).
        # The current segment starts at (idx_sym - ncodeunits(seg_sym)), so the
        # remainder including this segment is path[start:ncodeunits(path)].
        handler_call = Expr(:call, esc(child.handler), req_sym, new_parsed_vars...)
        push!(exprs, quote
            if length($(seg_sym)) != 0
                $(var_sym) = view($(path_sym), ($(idx_sym) - ncodeunits($(seg_sym))) : ncodeunits($(path_sym)))
                return $(handler_call)
            end
        end)
    end

    return Expr(:block, exprs...)
end

function _extractroutes(block)
    http_routes = []
    ws_routes = []
    for line in block.args
        line isa LineNumberNode && continue
        if line isa Expr && line.head == :call
            method_name = line.args[1]
            path = line.args[2]

            method_sym = Symbol(lowercase(String(method_name)))
            if method_sym == :ws
                # WS("/chat", on_message=..., on_open=..., on_close=...)
                kwargs = Dict{Symbol,Any}()
                for i in 3:length(line.args)
                    arg = line.args[i]
                    if arg isa Expr && arg.head == :kw
                        kwargs[arg.args[1]] = arg.args[2]
                    end
                end
                # Simplify: if only 3 args and 3rd is NOT a kw, assume on_message
                if length(line.args) == 3 && !(line.args[3] isa Expr && line.args[3].head == :kw)
                    kwargs[:on_message] = line.args[3]
                end
                push!(ws_routes, (path, kwargs))
            else
                handler = line.args[3]
                push!(http_routes, (method_sym, path, handler))
            end
        end
    end
    return http_routes, ws_routes
end

"""
    @router AppType block

Generate a static router for `AppType`.
Routes are defined as: `METHOD("/path", handler)`
Example:
```julia
@router MyApp begin
    get("/", (req) -> Response(200, "OK"))
    get("/users/{id::Int}", (req, id) -> Response(200, "User \$id"))
end
```
"""
macro router(app_type::Symbol, block)
    http_routes, ws_routes = _extractroutes(block)
    (isempty(http_routes) && isempty(ws_routes)) && error("@router: no routes found in block")

    root = _buildtrie(http_routes)

    path_sym = gensym("path")
    req_sym = gensym("req")

    dispatch_body = _generatedispatch(root, :_, :_, path_sym, req_sym, Symbol[], true)

    async_handler_sym = Symbol("_async_", app_type, "_c_handler")
    sync_handler_sym = Symbol("_sync_", app_type, "_c_handler")

    handler_definitions = esc(quote
        function $async_handler_sym(conn::Ptr{Cvoid}, ev::Cint, ev_data::Ptr{Cvoid})::Cvoid
            ev == Mongoose.MG_EV_POLL && return nothing
            fn_data = Mongoose.mg_conn_get_fn_data(conn)
            fn_data == C_NULL && return nothing
            # GC-safe recovery: fn_data holds objectid token, not heap address
            server = Mongoose._lookupserver(UInt(fn_data))
            server === nothing && return nothing
            server = server::Mongoose.Async{$app_type}
            try
                Mongoose._dispatchev(server, ev, conn, ev_data)
            catch e
                @error "Event handler error" component="eventloop" exception=(e, Base.catch_backtrace())
            end
            return nothing
        end

        function $sync_handler_sym(conn::Ptr{Cvoid}, ev::Cint, ev_data::Ptr{Cvoid})::Cvoid
            ev == Mongoose.MG_EV_POLL && return nothing
            fn_data = Mongoose.mg_conn_get_fn_data(conn)
            fn_data == C_NULL && return nothing
            # GC-safe recovery: fn_data holds objectid token, not heap address
            server = Mongoose._lookupserver(UInt(fn_data))
            server === nothing && return nothing
            server = server::Mongoose.Server{$app_type}
            try
                Mongoose._dispatchev(server, ev, conn, ev_data)
            catch e
                @error "Event handler error" component="eventloop" exception=(e, Base.catch_backtrace())
            end
            return nothing
        end

        Mongoose._cfnasync(::Type{$app_type}) = @cfunction($async_handler_sym, Cvoid, (Ptr{Cvoid}, Cint, Ptr{Cvoid}))
        Mongoose._cfnsync(::Type{$app_type}) = @cfunction($sync_handler_sym, Cvoid, (Ptr{Cvoid}, Cint, Ptr{Cvoid}))
    end)

    quote
        struct $(esc(app_type)) <: Mongoose.StaticRouter end

        $handler_definitions

        # --- Static Router Dispatch ---
        function Mongoose._dispatchstatic(::$(esc(app_type)), $(req_sym)::Mongoose.AbstractRequest)::Mongoose.Response
            $(path_sym) = Mongoose._stripquery($(req_sym).uri)

            $(dispatch_body)

            return Mongoose.Response(Plain, "404 Not Found"; status=404)
        end

        # --- Static WebSocket Dispatch ---
        function Mongoose._wsupgrade(::$(esc(app_type)), uri::String)::Union{Mongoose.WsEndpoint,Nothing}
            $(Expr(:block, [
                quote
                    if uri == $path
                        return Mongoose.WsEndpoint(; $([Expr(:kw, k, esc(v)) for (k, v) in kwargs]...))
                    end
                end for (path, kwargs) in ws_routes
            ]...))
            return nothing
        end

        $(if !isempty(ws_routes)
            :(Mongoose._haswsroutes(::$(esc(app_type))) = true)
        end)
    end
end
