"""
    Static router — compile-time route dispatch via @routes macro.
    Generates a monolithic Prefix Trie AST dispatch function for juliac --trim=safe AOT compilation.
    Adapted from Hodos.jl. Zero runtime dispatch, zero allocation.
"""

"""
    AbstractApp — Base type for static app types generated by @routes.
"""
abstract type AbstractApp end

"""
    NoApp — Sentinel type indicating no static app is configured.
"""
struct NoApp end

"""
    static_dispatch(app, request) → HttpResponse
"""
function static_dispatch end

# --- Path matching helpers (used by generated code) ---

@inline function static_next_segment(path::AbstractString, start_idx::Int)
    len = ncodeunits(path)
    if start_idx > len
        return (view(path, 1:0), start_idx)
    end
    # skip leading slashes for normalization
    while start_idx <= len && codeunit(path, start_idx) == UInt8('/')
        start_idx += 1
    end
    if start_idx > len
        return (view(path, 1:0), start_idx)
    end
    
    # find next slash
    end_idx = start_idx
    while end_idx <= len && codeunit(path, end_idx) != UInt8('/')
        end_idx += 1
    end
    
    return (view(path, start_idx:end_idx-1), end_idx)
end

@inline function strip_query(uri::AbstractString)
    len = ncodeunits(uri)
    for i in 1:len
        codeunit(uri, i) == UInt8('?') && return SubString(uri, 1, i - 1)
    end
    return SubString(uri, 1, len)
end

# --- Compile-time Types and Trie Construction ---
struct RouteSegment
    is_variable::Bool
    value::String      
    type::Union{Type, Symbol}
end

mutable struct RouterNode
    static_children::Dict{String, RouterNode}
    variable_child::Union{Tuple{RouteSegment, RouterNode}, Nothing}
    wildcard_child::Union{Tuple{String, RouterNode}, Nothing}
    handler::Union{Expr, Symbol, Nothing}

    RouterNode() = new(Dict{String, RouterNode}(), nothing, nothing, nothing)
end

function parse_route_template(path::String)
    segments = RouteSegment[]
    parts = split(path, '/', keepempty=false)
    for part in parts
        if startswith(part, ":")
            name = part[2:end]
            push!(segments, RouteSegment(true, String(name), SubString{String}))
        elseif startswith(part, "{") && endswith(part, "}")
            inner = part[2:end-1]
            if occursin("::", inner)
                name, typestr = split(inner, "::", limit=2)
                push!(segments, RouteSegment(true, String(name), Symbol(typestr)))
            else
                push!(segments, RouteSegment(true, String(inner), SubString{String}))
            end
        elseif startswith(part, "*")
            name = part[2:end]
            push!(segments, RouteSegment(true, String(name), Vector{String}))
        else
            push!(segments, RouteSegment(false, String(part), Nothing))
        end
    end
    return segments
end

function build_trie(routes)
    root = RouterNode()
    for (method_sym, path, handler) in routes
        segments = parse_route_template(path)
        # We model the method as the first segment essentially, to share the trie.
        method_seg = RouteSegment(false, String(method_sym), Nothing)
        segments = [method_seg; segments]
        
        node = root
        for seg in segments
            if seg.is_variable
                if seg.type == Vector{String}
                    if node.wildcard_child === nothing
                        node.wildcard_child = (seg.value, RouterNode())
                    end
                    node = node.wildcard_child[2]
                else
                    if node.variable_child === nothing
                        node.variable_child = (seg, RouterNode())
                    end
                    node = node.variable_child[2]
                end
            else
                if !haskey(node.static_children, seg.value)
                    node.static_children[seg.value] = RouterNode()
                end
                node = node.static_children[seg.value]
            end
        end
        node.handler = handler
    end
    return root
end

function generate_dispatch_node(node::RouterNode, seg_sym::Symbol, idx_sym::Symbol, path_sym::Symbol, req_sym::Symbol, parsed_vars::Vector{Symbol})
    exprs = []
    
    # 1. Exact match reached
    if node.handler !== nothing
        handler_call = Expr(:call, esc(node.handler), req_sym, parsed_vars...)
        push!(exprs, quote
            if length($(seg_sym)) == 0
                return $(handler_call)
            end
        end)
    end
    
    # 2. Static children
    if !isempty(node.static_children)
        static_blocks = []
        for (val, child) in node.static_children
            next_seg = gensym("seg")
            next_idx = gensym("idx")
            child_expr = generate_dispatch_node(child, next_seg, next_idx, path_sym, req_sym, parsed_vars)
            
            push!(static_blocks, quote
                if $(seg_sym) == $val
                    $(next_seg), $(next_idx) = static_next_segment($(path_sym), $(idx_sym))
                    $(child_expr)
                end
            end)
        end
        push!(exprs, Expr(:block, static_blocks...))
    end
    
    # 3. Variable child
    if node.variable_child !== nothing
        seg, child = node.variable_child
        var_sym = gensym(seg.value)
        next_seg = gensym("seg")
        next_idx = gensym("idx")
        
        new_parsed_vars = copy(parsed_vars)
        push!(new_parsed_vars, var_sym)
        
        child_expr = generate_dispatch_node(child, next_seg, next_idx, path_sym, req_sym, new_parsed_vars)
        
        # In Mongoose, we default variables to SubString (zero-copy) for performance
        parse_expr = if seg.type == SubString{String} || seg.type == String || seg.type == :String
            quote
                $(var_sym) = $(seg_sym) # use the view directly
            end
        else
            quote
                $(var_sym) = Base.parse($(seg.type), String($(seg_sym)))
            end
        end
        
        push!(exprs, quote
            if length($(seg_sym)) != 0
                $(parse_expr)
                $(next_seg), $(next_idx) = static_next_segment($(path_sym), $(idx_sym))
                $(child_expr)
            end
        end)
    end
    
    # 4. Wildcard child
    if node.wildcard_child !== nothing
        val, child = node.wildcard_child
        var_sym = gensym(val)
        new_parsed_vars = copy(parsed_vars)
        push!(new_parsed_vars, var_sym)
        
        # A wildcard consumes the rest of the path, zero-copy
        handler_call = Expr(:call, esc(child.handler), req_sym, new_parsed_vars...)
        push!(exprs, quote
            if length($(seg_sym)) != 0
                # reconstruct remaining path from current idx
                # seg_sym is a view, and idx_sym is the NEXT index.
                # To get everything from the start of the current segment:
                $(var_sym) = view($(path_sym), ($(idx_sym) - length($(seg_sym)) - 1):sizeof($(path_sym)))
                return $(handler_call)
            end
        end)
    end
    
    return Expr(:block, exprs...)
end

function _extract_routes(block)
    routes = Tuple{Symbol, String, Any}[]
    for line in block.args
        line isa LineNumberNode && continue
        if line isa Expr && line.head == :call && line.args[1] == :(=>)
            pair_left = line.args[2]
            func = line.args[3]
            
            if pair_left isa Expr && pair_left.head == :call
                method_name = pair_left.args[1]
                path = pair_left.args[2]
                
                method_sym = Symbol(lowercase(String(method_name)))
                push!(routes, (method_sym, path, func))
            end
        end
    end
    return routes
end

macro routes(app_type::Symbol, block)
    routes = _extract_routes(block)
    isempty(routes) && error("@routes: no routes found in block")
    
    root = build_trie(routes)
    
    path_sym = gensym("path")
    req_sym = gensym("req")
    
    # Initial setup
    method_seg_sym = gensym("method_seg")
    method_idx_sym = gensym("method_idx")
    
    dispatch_body = generate_dispatch_node(root, method_seg_sym, method_idx_sym, path_sym, req_sym, Symbol[])
    
    quote
        struct $(esc(app_type)) <: AbstractApp end
        
        function Mongoose.static_dispatch(::$(esc(app_type)), $(req_sym)::AbstractRequest)::HttpResponse
            $(path_sym) = strip_query($(req_sym).uri)
            
            # The root expects `method` to be matched as the first segment
            $(method_seg_sym) = view(String($(req_sym).method), 1:length(String($(req_sym).method)))
            $(method_idx_sym) = 1
            
            $(dispatch_body)
            
            return HttpResponse(404, "Content-Type: text/plain\r\n", "404 Not Found")
        end
    end
end
