"""
    HTTP status code → reason phrase mapping.
    Inlined chain for hot-path status codes.
"""
@inline function statusreason(code::Int)::String
    code == 200 && return "OK"
    code == 201 && return "Created"
    code == 202 && return "Accepted"
    code == 204 && return "No Content"
    code == 206 && return "Partial Content"
    code == 301 && return "Moved Permanently"
    code == 302 && return "Found"
    code == 303 && return "See Other"
    code == 304 && return "Not Modified"
    code == 307 && return "Temporary Redirect"
    code == 308 && return "Permanent Redirect"
    code == 400 && return "Bad Request"
    code == 401 && return "Unauthorized"
    code == 402 && return "Payment Required"
    code == 403 && return "Forbidden"
    code == 404 && return "Not Found"
    code == 405 && return "Method Not Allowed"
    code == 406 && return "Not Acceptable"
    code == 407 && return "Proxy Authentication Required"
    code == 408 && return "Request Timeout"
    code == 409 && return "Conflict"
    code == 410 && return "Gone"
    code == 411 && return "Length Required"
    code == 412 && return "Precondition Failed"
    code == 413 && return "Payload Too Large"
    code == 414 && return "URI Too Long"
    code == 415 && return "Unsupported Media Type"
    code == 416 && return "Range Not Satisfiable"
    code == 417 && return "Expectation Failed"
    code == 418 && return "I'm a Teapot"
    code == 421 && return "Misdirected Request"
    code == 422 && return "Unprocessable Entity"
    code == 423 && return "Locked"
    code == 424 && return "Failed Dependency"
    code == 425 && return "Too Early"
    code == 426 && return "Upgrade Required"
    code == 428 && return "Precondition Required"
    code == 429 && return "Too Many Requests"
    code == 431 && return "Request Header Fields Too Large"
    code == 451 && return "Unavailable For Legal Reasons"
    code == 500 && return "Internal Server Error"
    code == 501 && return "Not Implemented"
    code == 502 && return "Bad Gateway"
    code == 503 && return "Service Unavailable"
    code == 504 && return "Gateway Timeout"
    code == 505 && return "HTTP Version Not Supported"
    code == 506 && return "Variant Also Negotiates"
    code == 507 && return "Insufficient Storage"
    code == 508 && return "Loop Detected"
    code == 510 && return "Not Extended"
    code == 511 && return "Network Authentication Required"
    return ""
end
