"""
    HTTP status code → reason phrase mapping.
    Inlined chain for hot-path status codes.
"""
@inline function status_reason(code::Int)::String
    code == 200 && return "OK"
    code == 201 && return "Created"
    code == 202 && return "Accepted"
    code == 204 && return "No Content"
    code == 206 && return "Partial Content"
    code == 301 && return "Moved Permanently"
    code == 302 && return "Found"
    code == 304 && return "Not Modified"
    code == 307 && return "Temporary Redirect"
    code == 308 && return "Permanent Redirect"
    code == 400 && return "Bad Request"
    code == 401 && return "Unauthorized"
    code == 403 && return "Forbidden"
    code == 404 && return "Not Found"
    code == 405 && return "Method Not Allowed"
    code == 408 && return "Request Timeout"
    code == 409 && return "Conflict"
    code == 413 && return "Payload Too Large"
    code == 415 && return "Unsupported Media Type"
    code == 422 && return "Unprocessable Entity"
    code == 429 && return "Too Many Requests"
    code == 500 && return "Internal Server Error"
    code == 502 && return "Bad Gateway"
    code == 503 && return "Service Unavailable"
    code == 504 && return "Gateway Timeout"
    return ""
end
