"""
    User-facing Server — unified API that wraps AsyncServer / SyncServer internals.

    The `Server` struct decouples routing configuration from runtime behavior.
    Routes are registered on a `Router`, the server is constructed with that router,
    and `start!` determines sync vs async mode via the `workers` keyword.

# Usage
```julia
router = Router()
route!(router, :get, "/hello", req -> Response(200, "", "Hello!"))

server = Server(router)
use!(server, cors_middleware())
start!(server; port=8080, workers=4)   # async with 4 workers
shutdown!(server)
start!(server; port=8080)              # sync (workers=0)
```
"""
mutable struct Server
    router::DynamicRouter
    ws_router::AbstractWsRouter
    static::StaticRouter
    middlewares::Vector{Function}
    timeout::Int
    max_body_size::Int
    drain_timeout_ms::Int
    nqueue::Int
    _runtime::Union{Nothing, AbstractServer}
end

"""
    Server(router=Router(); ws_router, timeout, max_body_size, drain_timeout_ms, nqueue)

Create a server for dynamic routing.

# Arguments
- `router::Router`: The HTTP router (created separately via `Router()`).

# Keyword Arguments
- `ws_router::WsRoute`: WebSocket router (default: `NoWsRouter()`).
- `timeout::Integer`: Event loop poll timeout in ms (default: `0`).
- `max_body_size::Integer`: Max request body size in bytes (default: 1 MB).
- `drain_timeout_ms::Integer`: Shutdown drain timeout in ms (default: 5000).
- `nqueue::Integer`: Channel buffer size for async mode (default: 1024).
"""
function Server(router::DynamicRouter=DynamicRouter();
                ws_router::AbstractWsRouter=NoWsRouter(),
                timeout::Integer=0,
                max_body_size::Integer=DEFAULT_MAX_BODY_SIZE,
                drain_timeout_ms::Integer=DEFAULT_DRAIN_TIMEOUT_MS,
                nqueue::Integer=1024)
    return Server(router, ws_router, NoStaticRouter(), Function[], Int(timeout),
                  Int(max_body_size), Int(drain_timeout_ms), Int(nqueue), nothing)
end

"""
    Server(app::AbstractApp; ws_router, timeout, max_body_size, drain_timeout_ms, nqueue)

Create a server for static routing (using the `@router` macro).

# Arguments
- `static::StaticRouter`: The compiled app type generated by `@router`.
"""
function Server(static::StaticRouter;
                ws_router::AbstractWsRouter=NoWsRouter(),
                timeout::Integer=0,
                max_body_size::Integer=DEFAULT_MAX_BODY_SIZE,
                drain_timeout_ms::Integer=DEFAULT_DRAIN_TIMEOUT_MS,
                nqueue::Integer=1024)
    return Server(DynamicRouter(), ws_router, static, Function[], Int(timeout),
                  Int(max_body_size), Int(drain_timeout_ms), Int(nqueue), nothing)
end

# --- Delegation methods ---

"""
    route!(server::Server, method, path, handler)

Register a route on the server's router. Equivalent to `route!(server.router, ...)`.
"""
function route!(server::Server, method::Symbol, path::AbstractString, handler::Function)
    route!(server.router, method, path, handler)
    return server
end

"""
    use!(server::Server, middleware)

Register a middleware function on the server.
"""
function use!(server::Server, middleware::Function)
    push!(server.middlewares, middleware)
    return server
end

"""
    ws!(server::Server, path; on_message, on_open, on_close)

Register a WebSocket endpoint on the server's WS router.
"""
function ws!(server::Server, path::AbstractString; on_message::Function, on_open::Union{Function,Nothing}=nothing, on_close::Union{Function,Nothing}=nothing)
    if server.ws_router isa NoWsRouter
        throw(ArgumentError("WebSocket support not configured. Pass ws_router=WsRouter() when creating the server."))
    end
    server.ws_router.routes[path] = WsEndpoint(on_message=on_message, on_open=on_open, on_close=on_close)
    return server
end

# --- Lifecycle ---

"""
    start!(server::Server; host, port, blocking, workers)

Start the server. The `workers` keyword determines the execution mode:
- `workers=0` (default): synchronous, single-threaded event loop.
- `workers=N` (N > 0): asynchronous with N worker threads.

The same server can be stopped and restarted with a different number of workers.

# Examples
```julia
start!(server; port=8080, workers=4)    # async
shutdown!(server)
start!(server; port=9090, workers=8)    # restart async with more workers
shutdown!(server)
start!(server; port=8080)               # restart as sync
```
"""
function start!(server::Server; host::AbstractString="127.0.0.1", port::Integer=8080, blocking::Bool=true, workers::Integer=0)
    server._runtime !== nothing && throw(ServerError("Server is already running. Call shutdown! first."))

    if workers > 0
        runtime = build_AsyncServer(server.static, server.ws_router, C_NULL,
                                    server.timeout, workers, server.nqueue,
                                    server.max_body_size, server.drain_timeout_ms;
                                    router=server.router)
    else
        runtime = build_SyncServer(server.static, server.ws_router, C_NULL,
                                   server.timeout, server.max_body_size,
                                   server.drain_timeout_ms;
                                   router=server.router)
    end

    # Copy user middlewares to the runtime
    append!(runtime.core.middlewares, server.middlewares)

    server._runtime = runtime
    start!(runtime; host=host, port=port, blocking=blocking)
    return server
end

"""
    shutdown!(server::Server)

Stop the server and release all resources. The server can be restarted with `start!`.
"""
function shutdown!(server::Server)
    runtime = server._runtime
    if runtime === nothing
        @info "Server not running. Nothing to do."
        return
    end
    shutdown!(runtime)
    server._runtime = nothing
    return
end
